#  ????????(???? Integer,Boolean,LocalDateTime)
#    ?????????datetime,???????????????????null,????????????????now()
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: now()
      logic-not-delete-value: null