
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: "null"
      logic-delete-field: logicDelTime
      logic-delete-value: "is not null"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.56.116.10:3306/hhd?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: hhd
    password: 111111
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  cache:
    redis:
      time-to-live: 300000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

aliyun:
  accessKeyId: "LTAI5tNbwSodZsassr2m2FaL"
  accessKeySecret: "cTQJlRxi34QPN1Wz0L48GRhADnkDHS"

server:
  port: 80
logging:
  level:
    root: error

